PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX att: <http://www.semanticweb.org/part-time-team/ontologies/2023/5/attendance-ontology#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

# DA_WebSemantico attendance frequency for STU_00001_MarioRossi
SELECT ((?tot_freq / ?tot * 100) AS ?percentage) WHERE {
	{
		SELECT (count(?lesson) AS ?tot_freq) WHERE {
			?da att:hasLesson ?lesson .
			?lesson att:hasAttendance ?attendance . 
			?attendance att:hasStudent att:STU_00001_MarioRossi .
			FILTER (?da = att:DA_WebSemantico)
		}
	}
		{
		SELECT (count(?lesson) AS ?tot) WHERE {
			?da att:hasLesson ?lesson .
			FILTER (?da = att:DA_WebSemantico)
		}
	}
}
