PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX att: <http://www.semanticweb.org/part-time-team/ontologies/2023/5/attendance-ontology#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

# DA_WebSemantico attendance stundents with at least 1 presences
SELECT ?stuid ?surname ?name WHERE {
	?da att:hasLesson ?lesson .
	?lesson att:hasAttendance ?attendance .
	{ ?attendance rdf:type att:AttendanceValid . } 
	UNION 
	{ ?attendance rdf:type att:AttendanceValidWithDelay . }

	?attendance att:hasStudent ?student .

	?student att:student-id ?stuid ;
		vcard:given-name ?name ;
		vcard:family-name ?surname .

	FILTER (?da = att:DA_WebSemantico)
}

group by ?student ?stuid ?name ?surname