PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX att: <http://www.semanticweb.org/part-time-team/ontologies/2023/5/attendance-ontology#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

# DA_WebSemantico attendance stundents with at least 1 presences
SELECT ?stuid ?surname ?name WHERE {
	?wrk att:hasLesson ?lesson .
	?lesson att:hasPin ?pin .
	?pin att:hasAttendance ?attendance .

	?attendance att:hasAttendant ?attendant ;
		rdf:type ?type .
	?type rdfs:subClassOf att:AttendanceValid .

	?attendance att:hasAttendant ?attendant .

	?attendant rdf:type att:Student ;
		att:student-id ?stuid ;
		vcard:given-name ?name ;
		vcard:family-name ?surname .

	FILTER (?wrk = att:WRK_CL_001_DA_WebSemantico_2023)
}

 GROUP BY ?student ?stuid ?name ?surname
 ORDER BY ?stuid
