PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX att: <http://www.semanticweb.org/part-time-team/ontologies/2023/5/attendance-ontology#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

# Description of this awesome query
SELECT ?pin ?code ?attendable ?expirationDate WHERE {
    ?attendable att:hasPin ?pin .
    ?pin att:creation-date ?creationDate ;
        att:expiration-date ?expirationDate ;
        att:pin-code ?code .

    BIND( xsd:dateTime("2023-06-26T11:42:00Z") AS ?queriedDateTime ) # Get current date time
    #BIND( now() AS ?queriedDateTime ) # Get current date time

    FILTER (?expirationDate > ?queriedDateTime)
    FILTER (?creationDate < ?queriedDateTime)
}

ORDER BY ?expirationDate
