PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX att: <http://www.semanticweb.org/part-time-team/ontologies/2023/5/attendance-ontology#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

# Exam turn register
SELECT ?student ?turn ?type WHERE {
    ?exam att:hasTurn ?turn .
    ?turn att:hasStudent ?student .

    OPTIONAL {
        ?turn att:hasPin ?pin . 
        ?pin att:hasAttendance ?attendance .

        ?attendance att:hasAttendant ?student;
            rdf:type ?type.
        
        ?type rdfs:subClassOf att:AttendanceValid .
    }


    FILTER (?exam = att:EX_WS_2023_06_26)
}

ORDER BY ?student
