name: Publish doc

on: 
    push:
        tags:
            - '*'
    workflow_dispatch:

concurrency: production

jobs:
    # test:
        # uses: lucagiorgettismp/SemanticWebAttendance/.github/workflows/test.yml@main
    
    publish:
        # needs: [test]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3.5.3
            - run: |
                python -m pip install -r requirements.txt
                python -m mkdocs build
            -   uses: ncipollo/release-action@v1.12.0
                with:
                    artifacts: "site/*"
                    body: "Release"
                    generateReleaseNotes: true
            -   uses: actions/upload-pages-artifact@v1.0.7
                with:
                    path: ./site
            -   name: Deploy to Github Pages
                id: deployment
                uses: actions/deploy-pages@v1.2.3
